### ISSUE TITLE
How do I loop with two variables

### ISSUE THREAD

**Issue by Melcatus** [Melcatus/genomic_cotton#4]

**Comment by Melcatus** [comment]
**In the scrip data_cleaning.sh : Make to clean all samples without copying and pasting. In the loop two variables must be defined according to the path of R1 and R2.** 

**Script:** [/bin/data_cleaning.sh](https://github.com/Melcatus/genomic_cotton/blob/master/bin/data_cleaning.sh)  
**Data:** 
../data/R1
../data/R2
**The names of my samples are:** 

../data/R1
A01_1.fastq.gz
C01_1.fastq.gz
A02_1.fastq.gz
A03_1.fastq.gz
C02_1.fastq.gz

../data/R2
A01_2.fastq.gz
C01_2.fastq.gz
A02_2.fastq.gz
A03_2.fastq.gz
C02_2.fastq.gz


The command is: 
``` 
bbduk.sh -Xmx2g threads=1 in1=../data/R1/GhVer_R1.fastq.gz in2=../data/R2/GhVer_R2.fastq.gz out1=../data/seq_clean/R1/GhVer_R1_filter.fastq.gz out2=../data/R2/GhVer_R2_filter.fastq.gz ref=/resources/adapters.fa tpe tbo 

```

I tryed do a loop:

First ...
```
#!/bin/bash/

# This script is for data cleaning using BBTools.
# Run this script from directory /bin/  and  the sequences they are in /data/R1 and /data/R2
# Prerequisites: install BBTools 38.49

# 1. Create output directories 
mkdir -p ../data/seq_clean
mkdir -p ../data/seq_clean/R1
mkdir -p ../data/seq_clean/R2

# 2. Eliminate adapters

for i in *.fastq.gz;
do bbduk.sh -Xmx2g threads=1 in1=../data/R1/$i in2=../data/R2/$i out1=../data/seq_clean/R1/$i out2=../data/R2/$i ref=/resources/adapters.fa tpe tbo

```
ERROR: 

```
Executing jgi.BBDuk [-Xmx2g, threads=1, in1=../data/R1/*.fastq.gz, in2=../data/R2/*.fastq.gz, out1=../data/seq_clean/R1/*.fastq.gz, out2=../data/R2/*.fastq.gz, ref=/home/mel/Descargas/BBMap_38.49/bbmap/resources/adapters.fa, tpe, tbo]
Version 38.49

Set threads to 1
Exception in thread "main" java.lang.RuntimeException: Can't read file '../data/R1/*.fastq.gz'
	at shared.Tools.testInputFiles(Tools.java:1020)
	at jgi.BBDuk.<init>(BBDuk.java:919)
	at jgi.BBDuk.main(BBDuk.java:76)
```

then i tryed defined the two variables into loop:

```
# 2. Eliminate adapters
for i in ../data/R1/*.fastq.gz;
for z in ../data/R2/*.fastq.gz; 
do /home/mel/Descargas/BBMap_38.49/bbmap/bbduk.sh -Xmx2g threads=1 in1=../data/R1/$i in2=../data/R2/$z out1=../data/seq_clean/R1/$i out2=../data/R2/$z ref=/home/mel/Descargas/BBMap_38.49/bbmap/resources/adapters.fa tpe tbo
done
```

ERROR
```
prub_script1.sh: línea 14: error sintáctico cerca del elemento inesperado `for'
prub_script1.sh: línea 14: `for z in ../data/R2/*.fastq.gz

```
And, i tryed defined variables outside the loop...

```
dir1=../data/R1/*.fastq.gz
dir2=../data/R2/*.fastq.gz
for i in $dir1 $dir2;
do /home/mel/Descargas/BBMap_38.49/bbmap/bbduk.sh -Xmx2g threads=1 in1=../data/R1/$i in2=../data/R2/$i out1=../data/seq_clean/R1/$i out2=../data/R2/$i ref=/home/mel/Descargas/BBMap_38.49/bbmap/resources/adapters.fa tpe tbo
done

```
So...

```
Can't read file '../data/R1/../data/R2/GhY3-1_R2.fastq.gz'

```

I don’t know how to solve it :(

**Comment by AliciaMstt** [comment]
First clue:

You can write a regular expression to  find the first part of the file names and use this as an array in your loop. The regular expression will be `ls | grep -oE "\w*_"`.

What the above command does:

`ls |` lists the files and pipes it to grep
`grep` looks for a pattern written with a regular expression (flag `-E`) and prints the output found (only the part found, not the whole file found, flag `-o`). 
`"\w*_"` is the regular expression to be found. In this case `\w` means word character (letters, numbers and _). The `\` is used to escape the `w` so that grep knows we are using it as a metacharacter and not as a w. Then `*` means any number of the previous metacharacter, until it finds a `_`. In short `grep -oE "\w*_"` will give you the name of your samples up until before the `2.fastq.gz` and `1.fastq.gz`.

For more details check [these notes on regular expressions](https://github.com/AliciaMstt/BioinfinvRepro/blob/2018-II/Unidad2/Unidad2_IntroduccionUnixShell.md#regular-expressions-y-b%C3%BAsqueda-de-patrones-grep)

**Comment by Martinez-Gregorio-Hector** [comment]
We can resolve this script as follows.

First, create a directory **../data/clean/** when you put your results
In the second step **# 2. Eliminate adapters** modify the loop.
Establish `fileprefix=$(ls ../data | grep -oE "\w*_" | uniq)` to modify the loop and the expression, it looks like 

```
fileprefix=$(ls ../data | grep -oE "\w*_" | uniq)
for R in $fileprefix; do
bbmap/bbduk.sh -Xmx2g threads=1 in1=../data/${R}1.fastq.gz in2=../data/${R}2.fastq.gz out1=../data/clean/${R}1.fastq.gz out2=../data/clean/${R}2.fastq.gz ref=/bbmap/resources/adapters.fa tpe tbo;
done
```

With this expression your command would run.

**Comment by AliciaMstt** [comment]
Side comment: if you have few samples, it is not necessary to use a regular expression, you can just use something like:

```
for R in $(A01_R C01_R A02_R); do
bbmap/bbduk.sh -Xmx2g threads=1 in1=../data/${R}1.fastq.gz in2=../data/${R}2.fastq.gz out1=../data/clean/${R}1.fastq.gz out2=../data/clean/${R}2.fastq.gz ref=/bbmap/resources/adapters.fa tpe tbo;
done
```
